
from typing import Dict, List, Any

def generate_citations_text(presentation_data: Dict[str, Any]) -> str:
    """
    Extracts citations from presentation data and formats them into a text string.
    
    Args:
        presentation_data (Dict): The full presentation JSON object.
        
    Returns:
        str: Formatted citation text.
    """
    project_name = presentation_data.get("project_code_name", "Unknown Project")
    sector = presentation_data.get("sector", "Unknown Sector")
    
    lines = []
    lines.append(f"Citations for Project: {project_name}")
    lines.append(f"Sector: {sector}")
    lines.append("=" * 50)
    lines.append("")
    
    # Track unique citations to avoid redundancy if desired, 
    # but initially we want to map them to slides/blocks for context.
    
    slides = presentation_data.get("slides", [])
    for slide in slides:
        slide_number = slide.get("slide_number", "?")
        slide_title = slide.get("title", "Untitled Slide")
        
        lines.append(f"Slide {slide_number}: {slide_title}")
        lines.append("-" * 30)
        
        blocks = slide.get("blocks", [])
        if not blocks:
            lines.append("  (No blocks found)")
            
        for block in blocks:
            heading = block.get("heading", "Untitled Block")
            citation = block.get("citation", "No citation provided")
            
            # clean formatting
            if citation and citation.strip():
                lines.append(f"  • Block: {heading}")
                lines.append(f"    Source: {citation}")
            else:
                lines.append(f"  • Block: {heading}")
                lines.append(f"    Source: [Missing]")
        
        lines.append("") # Empty line between slides
        
    lines.append("=" * 50)
    lines.append("Generated by Kelp Agent")
    
    return "\n".join(lines)
